name: flowershop
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  http: ^1.2.1
  flutter_riverpod: ^2.5.1
#  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.6
  shimmer: ^3.0.0
  firebase_core: ^3.9.0
  supabase_flutter: ^2.8.3
  loading_animation_widget: ^1.3.0
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  connectivity_plus: ^6.1.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  place_picker_google: ^0.0.14
  google_maps_flutter: ^2.10.0
  firebase_messaging: ^15.2.1
  flutter_phoenix: ^1.1.1
  easy_localization: ^3.0.7+1
  location: ^7.0.1
  geolocator: ^13.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/font/
    - assets/translations/
    - assets/icon/
    - assets/images/
    - assets/images/bouquet/
    - assets/images/categories/
    - assets/images/icons/
    - assets/images/make-bouquet/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
